=== NereidaRO/1-DAM-PI-LDM/XSD/Averias.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="listadoAveria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="averia" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int"/>
                            <xs:element name="numeroSerie" type="xs:ID"/>
                            <xs:element name="fechaReporte" type="xs:date"/>
                            <xs:element name="descripcion" type="xs:string"/>
                            <xs:element name="duracion" type="xs:int"/>
                            <xs:element name="tipo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Eléctrico"/>
                                        <xs:enumeration value="Mecánico"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="operario" type="xs:string"/>
                            <xs:element name="mecanico" type="xs:string"/>
                            <xs:element name="coste" type="xs:int"/>
                            <xs:element name="fechaResolucion" type="xs:date"/>
                            <xs:element name="estado">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Resuelto"/>
                                        <xs:enumeration value="Detectada"/>
                                        <xs:enumeration value="En reparacion"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="comentarios" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence> 
        </xs:complexType>
    </xs:element>
</xs:schema>

=== NereidaRO/1-DAM-PI-LDM/XSD/Averias.xml
<?xml version="1.0" encoding="UTF-8"?>
<listadoAveria xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="Averias.xsd">
    <!--Eran los datos de entrada y
    salida; las etiquetas XML son "bolsillos" para guardar lo que mandemos/recibamos de la BDD-->
    <averia>
        <id>45187</id>
        <numeroSerie>SN4578</numeroSerie>
        <fechaReporte>2025-01-02</fechaReporte>
        <descripcion>Fallo del encendido</descripcion>
        <duracion>48</duracion>
        <tipo>Eléctrico</tipo>
        <operario>Ana vázquez</operario>
        <mecanico>Carlos López</mecanico>
        <coste>125</coste>
        <fechaResolucion>2025-01-04</fechaResolucion>
        <estado>Resuelto</estado>
        <comentarios>Reemplazo de pieza quemada.</comentarios>
    </averia>
    <averia>
        <id>72156</id>
        <numeroSerie>SN12345</numeroSerie>
        <fechaReporte>2025-01-15</fechaReporte>
        <descripcion>Fallo en motor</descripcion>
        <duracion>6</duracion>
        <tipo>Eléctrico</tipo>
        <operario>Juan Pérez</operario>
        <mecanico>Carlos López</mecanico>
        <coste>500</coste>
        <fechaResolucion>2025-01-16</fechaResolucion>
        <estado>Resuelto</estado>
        <comentarios>Se reemplazó el motor principal.</comentarios>
    </averia>
    <averia>
        <id>01342</id>
        <numeroSerie>SN2815</numeroSerie>
        <fechaReporte>2025-01-10</fechaReporte>
        <descripcion>Pieza suelta</descripcion>
        <duracion>1</duracion>
        <tipo>Mecánico</tipo>
        <operario>Isabel Urtia</operario>
        <mecanico>Marina Campos</mecanico>
        <coste>0</coste>
        <fechaResolucion>2025-01-10</fechaResolucion>
        <estado>Resuelto</estado>
        <comentarios>Ajuste de la pieza</comentarios>
    </averia>
</listadoAveria>
