=== NereidaRO/1-DAM-PI-LDM/XSD/detalleMaquina.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="detalleMaquinas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="detalleMaq">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="maquina" type="xs:string"/>
                            <xs:element name="id" type="xs:string"/>
                            <xs:element name="tipo" type="xs:string"/>
                            <xs:element name="estado" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Activa"/>
                                        <xs:enumeration value="Inactiva"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="descripcion" type="xs:string"/>
                            <xs:element name="ubicacion" type="xs:string"/>
                            <xs:element name="operarioAsignado" type="xs:string"/>
                            <xs:element name="horasUso" type="xs:string"/>
                            <xs:element name="proximoMantenimiento" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== NereidaRO/1-DAM-PI-LDM/XSD/detalleMaquina.xml
<?xml version="1.0" encoding="UTF-8"?>
<detalleMaquinas xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="detalleMaquina.xsd">
    <!--Eran los datos de entrada y
    salida; las etiquetas XML son "bolsillos" para guardar lo que mandemos/recibamos de la BDD-->
    <detalleMaq>
        <maquina>Máquina 1</maquina>
        <id>45187</id>
        <tipo>Cortadora industrial</tipo>
        <estado>Activa</estado>
        <descripcion>Máquina utilizada para el corte de materiales metálicos. Es esencial para la
            línea de producción.</descripcion>
        <ubicacion>Planta A</ubicacion>
        <operarioAsignado>Ana Vázquez</operarioAsignado>
        <horasUso>2500 horas</horasUso>
        <proximoMantenimiento>2025-06-15</proximoMantenimiento>
    </detalleMaq>
</detalleMaquinas>
