=== NereidaRO/1-DAM-PI-LDM/XSD/User-New.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="User-New">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entrada">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="dob" type="xs:date" />
                            <xs:element name="edad" type="xs:int" />
                            <xs:element name="direccion" type="xs:string" />
                            <xs:element name="nif">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern
                                            value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="rol">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="admin" />
                                        <xs:enumeration value="operario" />
                                        <xs:enumeration value="mecanico" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value=".+@.+\..+"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="telefono" minOccurs="1" maxOccurs="2">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern
                                            value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== NereidaRO/1-DAM-PI-LDM/XML/User-New.xml
<?xml version="1.0" encoding="UTF-8"?>
<User-New xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../XSD/User-New.xsd"> <!--Se
    trata de un formulario de
    envÃ­o de datos a BDD-->
    <entrada>
        <nombre>Ejemplo</nombre>
        <dob>2000-01-01</dob>
        <edad>25</edad>
        <direccion>Calle Ejemplo, 3</direccion>
        <nif>12345678Z</nif>
        <rol>admin</rol>
        <email>ejemplo@taller.com</email>
        <telefono>666666666</telefono>
        <telefono>999999999</telefono>
    </entrada>
</User-New>
